### ISSUE TITLE
question with the election

### ISSUE THREAD

**Issue by a1242902560** [PowerJob/PowerJob#154]
If a new worker is connected to a service, but the service finds that its grouping corresponding service is not reachable, its  stand-alone task will  be called by both servers?  Until the next time "ServerDiscoveryService.discovery()" ?

Please pay attention on issues you submitted, because we maybe need more details.

**Comment by KFCFans** [comment]
Generally speaking, a server is unreachable most likely because the server is down, which does not cause duplicate scheduling.

Of course, there are cases of unreachable due to network fluctuations, which may cause duplicate scheduling at this time, but this is also expected. In fact, high availability is often accompanied by duplicate executions.

In a distributed environment, it is very important to make every interface idempotent, and the same is true in PowerJob for each job.
